"""Action and tab icons of the design system (docs/design.md).

One source of truth: 24×24 line icons drawn with strokes (currentColor),
generated into
  engine/design/icons/<key>.svg                                  — masters, also used by the site and mockups
  engine/androidApp/src/main/res/drawable/ic_<key>.xml           — Android vector drawables
  engine/iosApp/Tz/Assets.xcassets/<key>.imageset                — iOS template images (vector)
Run: python3 engine/design/icons.py
"""
import json, os

STROKE = 1.8
ICONS = {
    "north": "M12 20V4M6 10l6-6 6 6",
    "east": "M4 12h16M14 6l6 6-6 6",
    "south": "M12 4v16M6 14l6 6 6-6",
    "west": "M20 12H4M10 6l-6 6 6 6",
    "up": "M3 20h5v-5h5v-5h5V5h3",
    "down": "M21 20h-5v-5h-5v-5H6V5H3",
    "enter": "M6 21V5a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v16M3 21h18M14.5 13h.5",
    "gallop": "M6 4v8a6 6 0 0 0 12 0V4M5 4h3M16 4h3M6 8.5h2M16 8.5h2",
    "attack": "M14.5 17.5L3 6V3h3l11.5 11.5M13 19l6-6M16 16l4 4M19 21l2-2M14.5 6.5L18 3h3v3l-3.5 3.5M5 14l4 4M7 17l-3 3M3 19l2 2",
    "flee": "M10 4H5v16h5M14 8l4 4-4 4M18 12H9",
    "talk": "M4 5h16v10h-9l-5 4v-4H4z",
    "look": "M2 12s3.6-6.5 10-6.5S22 12 22 12s-3.6 6.5-10 6.5S2 12 2 12zM15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0z",
    "take": "M12 3v11M7 9l5 5 5-5M4 16v4h16v-4",
    "drop": "M12 14V3M7 8l5-5 5 5M4 16v4h16v-4",
    "use": "M9.5 3h5M10 3v5.5l-5 8.5a2 2 0 0 0 1.7 3h10.6a2 2 0 0 0 1.7-3l-5-8.5V3M7 14.5h10",
    "equip": "M12 3l7 3v5.5c0 4.5-3 7.5-7 9.5-4-2-7-5-7-9.5V6zM12 7v10M8.5 11h7",
    "trade": "M12 4v16M8 20h8M5 7h14M5 7l-3 6a3 3 0 0 0 6 0zM19 7l-3 6a3 3 0 0 0 6 0z",
    "give": "M3 12h12M11 8l4 4-4 4M20 5v14",
    "mail": "M3 6h18v12H3zM3 6l9 7 9-7",
    "clan": "M6 21V3M6 4h12l-3 4 3 4H6",
    "tab-location": "M4 21h16M6 21V8M18 21V8M6 8V4h3v2h2V4h2v2h2V4h3v4M6 8h12M10 21v-4a2 2 0 0 1 4 0v4",
    "tab-hero": "M12 3a4 4 0 0 1 4 4v2a4 4 0 0 1-8 0V7a4 4 0 0 1 4-4zM4 21a8 8 0 0 1 16 0",
    "tab-bag": "M8.5 7h7M9 7L8 4h8l-1 3M9 7c-3 3-5 6-5 9a4 4 0 0 0 4 4h8a4 4 0 0 0 4-4c0-3-2-6-5-9M12 12v4",
    "tab-social": "M3 4h12v8H8l-4 3v-3H3zM9 15h7l4 3v-3h1V8h-3",
    "tab-world": "M3 6l6-2 6 2 6-2v14l-6 2-6-2-6 2zM9 4v14M15 6v14",
    "health": "M12 20s-7.5-4.6-7.5-10.2A4.3 4.3 0 0 1 12 7.2a4.3 4.3 0 0 1 7.5 2.6C19.5 15.4 12 20 12 20z",
    "mana": "M12 3s6 7 6 11.2a6 6 0 0 1-12 0C6 10 12 3 12 3z",
    "rest": "M6 3h12M6 21h12M7.5 3v3l4.5 6 4.5-6V3M7.5 21v-3l4.5-6 4.5 6v3",
    "gold": "M5 7a7 3 0 1 0 14 0 7 3 0 1 0-14 0zM5 7v5c0 1.7 3.1 3 7 3s7-1.3 7-3V7M5 12v5c0 1.7 3.1 3 7 3s7-1.3 7-3v-5",
    "settings": "M4 6h10M18 6h2M16 4v4M4 12h4M12 12h8M10 10v4M4 18h12M20 18h0M18 16v4",
}

HERE = os.path.dirname(os.path.abspath(__file__))
ENGINE = os.path.dirname(HERE)


def svg(d, color="currentColor", size=24):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" viewBox="0 0 24 24" fill="none" '
            f'stroke="{color}" stroke-width="{STROKE}" stroke-linecap="round" stroke-linejoin="round"><path d="{d}"/></svg>\n')


def vector(d):
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by engine/design/icons.py — edit the icon there. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp" android:height="24dp" android:viewportWidth="24" android:viewportHeight="24">
    <path android:pathData="{d}" android:fillColor="#00000000" android:strokeColor="#FF000000"
        android:strokeWidth="{STROKE}" android:strokeLineCap="round" android:strokeLineJoin="round" />
</vector>
'''


def check_tokens():
    """The keys must match tz.shared.Design.ICONS."""
    import re
    kt = open(os.path.join(ENGINE, "shared/src/commonMain/kotlin/tz/shared/Design.kt")).read()
    block = kt[kt.index("val ICONS"):]
    keys = re.findall(r'"([a-z-]+)" to "', block[:block.index("\n    )")])
    assert keys == list(ICONS), f"Design.ICONS and icons.py differ: {set(keys) ^ set(ICONS)}"


def main():
    check_tokens()
    out_svg = os.path.join(HERE, "icons"); os.makedirs(out_svg, exist_ok=True)
    out_and = os.path.join(ENGINE, "androidApp/src/main/res/drawable"); os.makedirs(out_and, exist_ok=True)
    cat = os.path.join(ENGINE, "iosApp/Tz/Assets.xcassets"); os.makedirs(cat, exist_ok=True)
    with open(os.path.join(cat, "Contents.json"), "w") as f:
        json.dump({"info": {"author": "xcode", "version": 1}}, f, indent=2)
    for key, d in ICONS.items():
        with open(os.path.join(out_svg, f"{key}.svg"), "w") as f:
            f.write(svg(d))
        with open(os.path.join(out_and, "ic_" + key.replace("-", "_") + ".xml"), "w") as f:
            f.write(vector(d))
        iset = os.path.join(cat, f"{key}.imageset"); os.makedirs(iset, exist_ok=True)
        with open(os.path.join(iset, f"{key}.svg"), "w") as f:
            f.write(svg(d, "#000000"))
        with open(os.path.join(iset, "Contents.json"), "w") as f:
            json.dump({"images": [{"filename": f"{key}.svg", "idiom": "universal"}],
                       "info": {"author": "xcode", "version": 1},
                       "properties": {"preserves-vector-representation": True, "template-rendering-intent": "template"}}, f, indent=2)
    print(len(ICONS), "icons")


if __name__ == "__main__":
    main()
